#!/bin/bash

# NixOS installer
# This script handles Nix package management and NixOS-specific configurations

set -euo pipefail

# Get script directory and source common functions
readonly SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/../../common/functions.sh"

# Distribution-specific configuration
readonly DISTRO="$1"

# NixOS configuration
readonly NIX_CONFIG_DIR="/etc/nixos"
readonly USER_CONFIG_DIR="$HOME/.config/nixpkgs"

# Common Nix packages
declare -A NIX_PACKAGES=(
    ["base"]="git curl wget zsh neofetch htop tree unzip"
    ["development"]="nodejs npm python3 gcc gnumake"
    ["media"]="vlc firefox"
    ["editors"]="vscode vim neovim"
)

# Update system
update_system() {
    info "Updating NixOS system..."
    
    # Update channels
    sudo nix-channel --update
    show_progress 1 3 "Updating channels"
    
    # Rebuild system configuration
    if [[ -f "$NIX_CONFIG_DIR/configuration.nix" ]]; then
        sudo nixos-rebuild switch
        show_progress 2 3 "Rebuilding system"
    fi
    
    # Garbage collection
    nix-collect-garbage -d
    show_progress 3 3 "Cleaning up old generations"
    
    wait_for_system 5 "Allowing system to stabilize after updates"
    success "System updated successfully"
}

# Setup Nix channels
setup_channels() {
    info "Configuring Nix channels..."
    
    # Add unstable channel for latest packages
    if confirm "Add nixpkgs-unstable channel?" "y"; then
        sudo nix-channel --add https://nixos.org/channels/nixpkgs-unstable nixpkgs-unstable
        nix-channel --add https://nixos.org/channels/nixpkgs-unstable nixpkgs-unstable
        success "Unstable channel added"
    fi
    
    # Add home-manager channel
    if confirm "Add home-manager channel?" "y"; then
        nix-channel --add https://github.com/nix-community/home-manager/archive/master.tar.gz home-manager
        nix-channel --update
        success "Home-manager channel added"
    fi
}

# Create NixOS configuration backup
backup_configuration() {
    if [[ -f "$NIX_CONFIG_DIR/configuration.nix" ]]; then
        local backup_file="${NIX_CONFIG_DIR}/configuration.nix.backup.$(date +%Y%m%d_%H%M%S)"
        sudo cp "$NIX_CONFIG_DIR/configuration.nix" "$backup_file"
        success "Configuration backed up to: $backup_file"
    fi
}

# Generate enhanced NixOS configuration
generate_nixos_config() {
    if confirm "Generate enhanced NixOS configuration?" "y"; then
        info "Generating NixOS configuration..."
        
        backup_configuration
        
        # Create enhanced configuration
        sudo tee "$NIX_CONFIG_DIR/configuration.nix" > /dev/null << 'EOF'
# Enhanced NixOS Configuration
# Generated by Universal Linux Installer

{ config, pkgs, ... }:

{
  imports =
    [ # Include the results of the hardware scan.
      ./hardware-configuration.nix
    ];

  # Boot loader configuration
  boot.loader.systemd-boot.enable = true;
  boot.loader.efi.canTouchEfiVariables = true;

  # Networking
  networking.hostName = "nixos"; # Define your hostname.
  networking.networkmanager.enable = true;

  # Set your time zone.
  time.timeZone = "Europe/Paris";

  # Select internationalisation properties.
  i18n.defaultLocale = "en_US.UTF-8";
  i18n.extraLocaleSettings = {
    LC_ADDRESS = "en_US.UTF-8";
    LC_IDENTIFICATION = "en_US.UTF-8";
    LC_MEASUREMENT = "en_US.UTF-8";
    LC_MONETARY = "en_US.UTF-8";
    LC_NAME = "en_US.UTF-8";
    LC_NUMERIC = "en_US.UTF-8";
    LC_PAPER = "en_US.UTF-8";
    LC_TELEPHONE = "en_US.UTF-8";
    LC_TIME = "en_US.UTF-8";
  };

  # Enable the X11 windowing system.
  services.xserver.enable = true;

  # Enable the GNOME Desktop Environment.
  services.xserver.displayManager.gdm.enable = true;
  services.xserver.desktopManager.gnome.enable = true;

  # Configure keymap in X11
  services.xserver = {
    layout = "us";
    xkbVariant = "";
  };

  # Enable CUPS to print documents.
  services.printing.enable = true;

  # Enable sound with pipewire.
  sound.enable = true;
  hardware.pulseaudio.enable = false;
  security.rtkit.enable = true;
  services.pipewire = {
    enable = true;
    alsa.enable = true;
    alsa.support32Bit = true;
    pulse.enable = true;
  };

  # Enable touchpad support (enabled default in most desktopManager).
  # services.xserver.libinput.enable = true;

  # Define a user account. Don't forget to set a password with 'passwd'.
  users.users.user = {
    isNormalUser = true;
    description = "User";
    extraGroups = [ "networkmanager" "wheel" ];
    packages = with pkgs; [
      firefox
      thunderbird
    ];
  };

  # Allow unfree packages
  nixpkgs.config.allowUnfree = true;

  # List packages installed in system profile.
  environment.systemPackages = with pkgs; [
    # Essential tools
    git
    curl
    wget
    neofetch
    htop
    tree
    unzip
    
    # Development tools
    nodejs
    npm
    python3
    gcc
    gnumake
    
    # Editors
    vim
    neovim
    
    # Media
    vlc
    
    # System tools
    networkmanagerapplet
  ];

  # Some programs need SUID wrappers, can be configured further or are
  # started in user sessions.
  programs.mtr.enable = true;
  programs.gnupg.agent = {
    enable = true;
    enableSSHSupport = true;
  };

  # List services that you want to enable:

  # Enable the OpenSSH daemon.
  # services.openssh.enable = true;

  # Open ports in the firewall.
  # networking.firewall.allowedTCPPorts = [ ... ];
  # networking.firewall.allowedUDPPorts = [ ... ];
  # Or disable the firewall altogether.
  # networking.firewall.enable = false;

  # This value determines the NixOS release from which the default
  # settings for stateful data, like file locations and database versions
  # on your system were taken. It's perfectly fine and recommended to leave
  # this value at the release version of the first install of this system.
  system.stateVersion = "24.05"; # Did you read the comment?

  # Enable flakes and nix command
  nix.settings.experimental-features = [ "nix-command" "flakes" ];

  # Auto upgrade system
  system.autoUpgrade = {
    enable = true;
    allowReboot = false;
  };

  # Garbage collection
  nix.gc = {
    automatic = true;
    dates = "weekly";
    options = "--delete-older-than 30d";
  };
}
EOF
        
        success "Enhanced NixOS configuration generated"
        info "Please review and customize /etc/nixos/configuration.nix before rebuilding"
    fi
}

# Setup home-manager
setup_home_manager() {
    if confirm "Install and configure home-manager?" "y"; then
        info "Setting up home-manager..."
        
        # Install home-manager
        nix-channel --add https://github.com/nix-community/home-manager/archive/master.tar.gz home-manager
        nix-channel --update
        
        # Install home-manager
        nix-shell '<home-manager>' -A install
        
        # Create home-manager configuration directory
        mkdir -p "$USER_CONFIG_DIR"
        
        # Generate basic home-manager configuration
        tee "$USER_CONFIG_DIR/home.nix" > /dev/null << EOF
{ config, pkgs, ... }:

{
  # Home Manager needs a bit of information about you and the paths it should manage.
  home.username = "$USER";
  home.homeDirectory = "$HOME";

  # This value determines the Home Manager release that your configuration is
  # compatible with. This helps avoid breakage when a new Home Manager release
  # introduces backwards incompatible changes.
  home.stateVersion = "24.05";

  # Packages that should be installed to the user profile.
  home.packages = with pkgs; [
    # Development tools
    vscode
    discord
    spotify
    
    # Terminal tools
    zsh
    oh-my-zsh
    
    # Fonts
    nerdfonts
    
    # Browser
    google-chrome
  ];

  # Enable ZSH
  programs.zsh = {
    enable = true;
    enableAutosuggestions = true;
    enableCompletion = true;
    oh-my-zsh = {
      enable = true;
      plugins = [ "git" "docker" "kubectl" ];
      theme = "robbyrussell";
    };
  };

  # Git configuration
  programs.git = {
    enable = true;
    # userName = "Your Name";
    # userEmail = "your.email@example.com";
  };

  # Let Home Manager install and manage itself.
  programs.home-manager.enable = true;
}
EOF
        
        success "Home-manager configuration created"
        info "Edit ~/.config/nixpkgs/home.nix to customize your user environment"
    fi
}

# Install packages imperatively (for quick testing)
install_nix_packages() {
    if confirm "Install packages imperatively (not recommended for NixOS)?" "n"; then
        info "Select packages to install:"
        echo "  1) Visual Studio Code"
        echo "  2) Discord"
        echo "  3) Spotify"
        echo "  4) Google Chrome"
        echo "  5) GIMP"
        echo "  6) LibreOffice"
        echo "  s) Skip imperative installation"
        echo
        
        read -r -p "Enter your choice (comma-separated numbers): " choice
        
        local packages=()
        
        case "$choice" in
            s|S) return 0 ;;
            *)
                IFS=',' read -ra choices <<< "$choice"
                for c in "${choices[@]}"; do
                    c=$(echo "$c" | xargs)
                    case "$c" in
                        1) packages+=("vscode") ;;
                        2) packages+=("discord") ;;
                        3) packages+=("spotify") ;;
                        4) packages+=("google-chrome") ;;
                        5) packages+=("gimp") ;;
                        6) packages+=("libreoffice") ;;
                    esac
                done
                ;;
        esac
        
        # Install selected packages
        for package in "${packages[@]}"; do
            info "Installing $package..."
            if nix-env -iA "nixpkgs.$package"; then
                success "✅ $package installed"
            else
                error "❌ Failed to install $package"
            fi
        done
        
        warn "Note: Imperative package installation is not recommended on NixOS"
        warn "Consider adding packages to your configuration.nix or home.nix instead"
    fi
}

# Configure Nix settings
configure_nix() {
    if confirm "Configure Nix settings for better performance?" "y"; then
        info "Configuring Nix..."
        
        # Create nix.conf if it doesn't exist
        sudo mkdir -p /etc/nix
        
        local nix_conf="/etc/nix/nix.conf"
        
        # Enable experimental features
        if ! grep -q "experimental-features" "$nix_conf" 2>/dev/null; then
            echo "experimental-features = nix-command flakes" | sudo tee -a "$nix_conf" > /dev/null
            success "Experimental features enabled"
        fi
        
        # Configure substituters
        if ! grep -q "substituters" "$nix_conf" 2>/dev/null; then
            echo "substituters = https://cache.nixos.org/ https://nix-community.cachix.org" | sudo tee -a "$nix_conf" > /dev/null
            echo "trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= nix-community.cachix.org-1:mB9FSh9qf2dCimDSUo8Zy7bkq5CX+/rkCWyvRCYg3Fs=" | sudo tee -a "$nix_conf" > /dev/null
            success "Binary caches configured"
        fi
        
        # Set max jobs
        local cpu_cores
        cpu_cores=$(nproc)
        if ! grep -q "max-jobs" "$nix_conf" 2>/dev/null; then
            echo "max-jobs = $cpu_cores" | sudo tee -a "$nix_conf" > /dev/null
            success "Max jobs set to $cpu_cores"
        fi
    fi
}

# Distribution-specific cleanup
cleanup_distribution_specific() {
    info "Cleaning up Nix store..."
    
    # Collect garbage
    nix-collect-garbage -d
    
    # Clean up old generations
    if confirm "Remove old system generations?" "y"; then
        sudo nix-collect-garbage -d
        # Clean boot menu entries
        sudo nixos-rebuild switch
    fi
    
    # Optimize nix store
    if confirm "Optimize Nix store (may take time)?" "y"; then
        nix-store --optimise
    fi
}

# Handle Node.js for NixOS
install_nodejs_nixos() {
    info "Node.js on NixOS should be managed through configuration files"
    
    if confirm "Show Node.js configuration examples?" "y"; then
        info "Add Node.js to your configuration.nix:"
        echo "  environment.systemPackages = with pkgs; [ nodejs npm ];"
        echo
        info "Or add to home.nix (home-manager):"
        echo "  home.packages = with pkgs; [ nodejs npm ];"
        echo
        info "For development environments, consider using nix-shell:"
        echo "  nix-shell -p nodejs npm"
    fi
}

# Main installation workflow
main() {
    info "Starting NixOS configuration"
    info "Note: NixOS uses declarative configuration management"
    
    # Configure Nix settings
    configure_nix
    
    # Setup channels
    setup_channels
    
    # Generate NixOS configuration
    generate_nixos_config
    
    # Setup home-manager
    setup_home_manager
    
    # Update system
    update_system
    
    # Install packages imperatively (not recommended)
    install_nix_packages
    
    # Handle Node.js
    install_nodejs_nixos
    
    # Setup development environment (limited on NixOS)
    if confirm "Show development environment setup for NixOS?" "y"; then
        info "Development environment on NixOS:"
        echo "  • Add packages to configuration.nix or home.nix"
        echo "  • Use nix-shell for temporary environments"
        echo "  • Use direnv + shell.nix for project-specific environments"
        echo "  • Consider using flakes for reproducible development"
    fi
    
    # System cleanup
    cleanup_system
    
    success "🎉 NixOS configuration completed!"
    echo
    info "Next steps:"
    echo "  1. Review and customize /etc/nixos/configuration.nix"
    echo "  2. Review and customize ~/.config/nixpkgs/home.nix (if using home-manager)"
    echo "  3. Run: sudo nixos-rebuild switch"
    echo "  4. Run: home-manager switch (if using home-manager)"
    echo
    
    if confirm "Rebuild system with new configuration now?" "y"; then
        sudo nixos-rebuild switch
        success "System rebuilt successfully!"
    fi
}

# Run main function with error handling
if ! main; then
    error "Configuration failed!"
    exit 1
fi
